config/routes.rb
Rails.application.routes.draw do
  get 'interests/index'

  get 'interests/show'

  get 'interests/edit'

  get 'interests/new'

  get 'users/profile'  #do we really need the above?

  devise_for :users

  get "users/:id/vote" => "users#vote", as: :upvote
  get 'users/:id/unvote' => 'users#unvote',as: :downvote

  resources :users do
    resources :interests
  end

  root to: 'users#index'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user

  def self.by_profession
    order(:profession)
  end

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :interest, dependent: :destroy
  validates_presence_of :first_name

  def self.by_name
    order(:first_name)
  end

  # def females_only
  #
  # end
  #
  # def males_only
  #
  # end

#   def upvote
#    @post = Post.find(params[:id])
#    @post.vote += 1
#    @post.save!
#    redirect_to root_path
#  end
#
#  def downvote
#    @post = Post.find(params[:id])
#    @post.vote += -1
#    @post.save!
#    redirect_to root_path
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :description << :gender
    devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :description << :gender
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  
  # def index
  #   @interests = Interest.where(user_id: params[:user_id])
  #   @interest = Interest.find(params[:id])
  # end

  def new
    @user = User.find(params[:user_id])
    # @interest = @user.interests.new
    @interest = Interest.new(user_id: params[:user_id])
  end
  # def new
  #   @post = Post.find(params[:post_id])
  #   @comment = @post.comments.new
  # end

  def create
    @interest = Interest.new(interest_params)
    @user = User.find(params[:user_id])
    # @interest = Interest.new(params[:id])
    if @interest.save
      redirect_to user_path(@user)
      # redirect_to user_interests_path(user_id: params[:user_id])
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @interest = Interest.find(params[:user_id])
  end

  def update
    @user = User.find(params[:user_id])
    @interest = Interest.find(params[:id])
    if @interest.update(interest_params)
      redirect_to user_path(@user)
      # redirect_to user_interests_path(user_id: params[:user_id])
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user)
    @interest = Interest.find(params[:id])
    if @interest.destroy
      redirect_to root_path
    else
      redirect_to user_path(@user)
    end
  end

  private

  def interest_params
    params.require(:interest).permit(:profession, :hobbies, :kids, :party, :user_id)
  end
  # def comment_params
  #   params.require(:comment).permit(:post_id, :name, :body)
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.by_name
    # @users_females = User.where(gender: 'female').females_only
    # @users_males = User.where(gender: 'male').males_only
  end

  def vote
    User.increment_counter(:votes, params[:id])
      redirect_to user_path(id: params[:id])
  end

  def unvote
    User.decrement_counter(:votes, params[:id])
    redirect_to user_path(id: params[:id])
  end

  def show
    @user = User.find(params[:id])
    @interests = Interest.where(user_id: params[:id])
  end

  def profile
    @user = User.find(current_user)
    # @user = User.find(params[:id])
    # @interests = Interest.where(user_id: params[:id])
    @interests = Interest.where(user_id: current_user)
  end

  private

  # Not sure if below should be commented out or not!!!!
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :password) #devise is requiring email and password FYI!
  end

  # def find_user
  #   @user = User.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/interests/_interestform.html.erb
<%= form_for [@user, @interest] do |f| %>
  <%= f.hidden_field :user_id %>

  <%= f.label :profession %>
  <%= f.text_field :profession %><br>

  <%= f.label :hobbies %>
  <%= f.text_field :hobbies %><br>

  <%= f.label :kids %>
  <%= f.text_field :kids %><br>
  <p>Like to Party: </p>
  <%= f.radio_button :party, true %>
  <%= f.label :party, "Yes", :value => "true" %>

  <%= f.radio_button :party, false %>
  <%= f.label :party, "No", :value => "false" %>
  <br>
  <hr />

  <%= f.submit %>
<% end %>

<!-- <div class="row">
   <form class="col s12">
     <div class="row">
       <div class="input-field col s6">
         <input placeholder="Placeholder" id="first_name" type="text" class="validate">
         <label for="first_name">First Name</label>
       </div>
       <div class="input-field col s6">
         <input id="last_name" type="text" class="validate">
         <label for="last_name">Last Name</label>
       </div>
     </div>
     <div class="row">
       <div class="input-field col s12">
         <input disabled value="I am not editable" id="disabled" type="text" class="validate">
         <label for="disabled">Disabled</label>
       </div>
     </div>
     <div class="row">
       <div class="input-field col s12">
         <input id="password" type="password" class="validate">
         <label for="password">Password</label>
       </div>
     </div>
     <div class="row">
       <div class="input-field col s12">
         <input id="email" type="email" class="validate">
         <label for="email">Email</label>
       </div>
     </div>
   </form>
 </div> -->

app/views/interests/edit.html.erb
<%= render partial: 'interests/interestform' %>
<!-- <ECHO= render 'interestform' %> -->

app/views/interests/index.html.erb
<p>If you arrived at this page we didn't do something right.</p>
<!-- <div class="row">
  <div class="col s10 offset-s1">
    <div class="card medium blue lighten-3">
      <div class="card-content white-text">
        <span class="card-title red-text"><%= current_user.first_name %> Interests:</span>
        <p class=interests>
          Profession:  <%= @interest.profession %>
          Hobbies:  <%= @interest.hobbies %>
          Kids:  <%= @interest.kids %>
      </div>
      <div class="card-action">
        <p class='btn interests-links'><ECHO= link_to 'Edit your profile interests', edit_user_interest_path(current_user, @interest) %></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
    <div class='col s10 offset-s1'>
      <div class="card medium blue lighten-3">
        <div class="card-content white-text">
            <span class='card-title red-text'><ECHO= current_user.first_name %> Interests: </span>
  <NONECHO @interests.each do |interest| %>

            <p class="interests">Profession:  <%= interest.profession %></p>
            <p class="interests">Hobbies:  <%= interest.hobbies %></p>
            <p class="interests">Kids:  <%= interest.kids %></p>
            <div class= "card-action">
              <p class='btn interests-links'><ECHO= link_to 'Edit your profile interests', edit_user_interest_path(current_user, interest) %></p>
  <NONECHO end %>
            </div>
        </div>
      </div>
    </div>
</div>

<div class='row'>
  <p class='btn interests-links'><ECHO= link_to 'Enter your profile interests', new_user_interest_path(current_user) %></p>
</div> -->

app/views/interests/new.html.erb
<header>
  <h1>Dating: Create New Interests</h1>
  <p class='options'><%= link_to 'Home', root_path %>
</header>

<%= render partial: 'interests/interestform' %>
<!-- <ECHO= render 'interestform' %> -->

app/views/interests/show.html.erb
<p>If you arrived at this page we didn't do something right.</p><!-- <div class="row">
  <div class="col s10 offset-s1">
    <div class="card medium blue lighten-3">
      <div class="card-content white-text">
        <span class="card-title red-text"><%= current_user.first_name %> Interests:</span>
        <p class=interests>
          Profession:  <%= @interest.profession %>
          Hobbies:  <%= @interest.hobbies %>
          Kids:  <%= @interest.kids %>
      </div>
      <div class="card-action">
        <p class='btn interests-links'><ECHO= link_to 'Edit your profile interests', edit_user_interest_path(current_user, @interest) %></p>
      </div>
    </div>
  </div>
</div> -->


<%= f.label :autolyse %><br />
<%= f.label :autolyse, "Yes", :value => "true"  %>
<%= f.radio_button :autolyse, true %>
<%= f.label :autolyse, "No", :value => "false" %>
<%= f.radio_button :autolyse, false, :checked => true %>

<%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "I'm over 21") %>

<% if params[:action] == 'new'
     go_to = user_interests_path(params[:user_id])
  else
    go_to = user_interest_path(params[:user_id], params[:id])
  end %>
<%= form_for @interest, url: go_to do |f| %>
  <%= f.label :profession %>
  <%= f.text_field :profession %>

  <%= f.label :hobbies %>
  <%= f.text_field :hobbies %>

  <%= f.label :kids %>
  <%= f.text_field :kids %>

  <%= f.radio_button :party, true %>
  <%= f.label :party, 'Do you like to party?' %>

  <%= f.radio_button :party, false %>
  <%= f.label :party, 'No party for you' %>
  <br />

  <%= f.hidden_field :user_id, value: params[:user_id] %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-wrapper grey darken-2">
     <a href="<% link_to 'what', users_path %>" class="brand-logo">Looking4Love</a>
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
     <ul class="right hide-on-med-and-down">
       <li><%= link_to('Edit account information', edit_user_registration_path) %></li>
       <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
     </ul>
     <ul class="side-nav" id="mobile-demo">
       <li><%= link_to('Edit account information', edit_user_registration_path) %></li>
       <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
     </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <title>Dating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <ul class="hmenu">
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </ul>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="head-info row blue darken-4">
    <br />
    <br />
      <h2 class="center amber-text text-accent-3">Check our all our users!</h2>
    <br />
    <br />
    <br />
</div>
  <div class="show-prof row blue darken-4">
    <p id="show-prof" class="show-prof amber-text text-accent-3 left waves-effect waves-light btn-large"><i class="material-icons left">cloud</i><%= link_to 'Show Profile', users_profile_path(current_user)%></p>
  </div>

  <div class ="container">
    <div class ="row">
      <% @users.each do |user| %>
        <div class='col s12 m4'>
          <div class="card small white">
            <div class="black-text">
              <span class="card-title amber-text text-accent-3"> <%= user.first_name %>'s Info:</span>
              <p> First Name: <%= user.first_name %></p>
              <p> Last Name: <%= user.last_name %></p>
              <p> Description: <%= user.description %></p>
              <p> Gender: <%= user.gender %></p>
              <div class='card-action center blue darken-2'>
                <p id="show-user" class='btn tooltipped' data-position='right' data-delay='50' data-tooltip='Click to interact with <%= user.first_name%>'><%= link_to 'User\'s profile', user_path(user) %></p>
            </div>
            </div>
          </div>
       </div>
      <% end %>
    </div>
  </div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<div class="container">
  <h2 class="amber-text text-accent-3"> <%= @user.first_name %></h2>
  <div class="row">
    <div class="col s12 m4">
      <div class="card medium">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="http://www.how-to-draw-cartoons-online.com/image-files/how-to-draw-a-heart.gif" height="250" width="42">
          </div>
          <div class="card-content blue darken-2">
            <span class="card-title activator amber-text text-accent-3">Click for more Info about <%= @user.first_name%><i class="material-icons right">more_vert</i></span>
            <p class="back-to-index"><%= link_to 'Back to all users', users_path %></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">User information<i class="material-icons right">close</i></span>
            <p>First name: <%= @user.first_name %></p>
            <p>Last name:<%= @user.last_name %></p>
          </div>
        </div>
    </div>
  </div>

  <% @interests.each do |interest|  %>
    <p class="amber-text text-accent-3">Profession:  <%= interest.profession %></p>
    <p class="amber-text text-accent-3">Hobbies:  <%= interest.hobbies %></p>
    <p class="amber-text text-accent-3">Kids:  <%= interest.kids %></p>
    <p class="amber-text text-accent-3">Likes to Party: <%= interest.party %></p>
    <div class="row">
      <span id="edit-interests" class="edit-interests white-text left waves-effect waves-light btn small"><i class="material-icons left">info</i><%= link_to 'Edit Interests', edit_user_interest_path(interest, @user) %></span>
      <span id="delete-interests" class="delete-interests white-text left waves-effect waves-light btn small"><i class="material-icons left">delete</i><%= link_to 'Delete Interests', user_interest_path(current_user, interest), method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </div>
  <% end %>
  <p class="add-interests"><%= link_to 'Add Interests', new_user_interest_path(@user) %></p><br>
</div>

app/views/users/show.html.erb
<div class="container offset-1">
  <h2 class="amber-text text-accent-3"> <%= @user.first_name %></h2>
  <div class="row">
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="http://www.how-to-draw-cartoons-online.com/image-files/how-to-draw-a-heart.gif" height="250" width="42">
        </div>
        <div class="card-content blue darken-2">
          <span class="card-title activator amber-text text-accent-3">Click for more Info about <%= @user.first_name%><i class="material-icons right">more_vert</i></span>
          <p class="back-to-index"><%= link_to 'Back to all users', users_path %></p>
          <p> Total Likes: <%= @user.votes %></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">User information<i class="material-icons right">close</i></span>
          <p>First name: <%= @user.first_name %></p>
          <p>Last name:<%= @user.last_name %></p>
        </div>
      </div>
          <% @interests.each do |interest|  %>
            <span class="amber-text text-accent-3">Profession:  <%= interest.profession %></p>
            <span class="amber-text text-accent-3">Hobbies:  <%= interest.hobbies %></p>
            <span class="amber-text text-accent-3">Kids:  <%= interest.kids %></p>
            <span class="amber-text text-accent-3">Likes to Party: <%= interest.party %></p>
          <% end %>
    </div>
  </div>
  <br />


  <div class="row">
    <span id='upvote' class="waves-effect waves-light btn"><%=link_to 'Like', upvote_path(params[:id]) %></span>
    <span id='downvote' class="waves-effect waves-light btn"><%=link_to 'Unlike', downvote_path(params[:id]) %></span>
  </div>

</div>